projects:
  aterbruketwebapp:
    schemaPath: amplify/backend/api/aterbruketwebapp/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/models.ts
        docsFilePath: src/graphql
        maxDepth: 4
extensions:
  amplify:
    version: 3
