export default [
  {
    name: "advertType",
    dataType: "text",
    fieldType: "radio",
    disabled: false,
    title: "Den är till för",
    required: true,
    option: [
      {
        name: "recycle",
        swe: ["Återbruk"],
        eng: ["Recycle"],
      },
      {
        name: "borrow",
        swe: ["Utlåning"],
        eng: ["Borrow"],
      },
    ],
  },
  {
    name: "images",
    dataType: "file",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Lägg till en bild",
  },
  {
    name: "title",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Rubrik",
    placeholder: "Döp annonsen...",
  },
  {
    name: "aterbruketId",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Återbruket ID",
    placeholder: "ex. 4435A",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "category",
    fieldType: "select",
    disabled: false,
    required: true,
    title: "Kategori / Typ av möbel",
    swe: [
      "Barnmöbler",
      "Bord",
      "Diverse",
      "Förvaringsmöbler",
      "Höj- och sänkbart skrivbord",
      "Kontorsstolar",
      "Reservdelar och Tillbehör",
      "Sittmöbler",
      "Skrivbord",
      "Soffor och Bänkar",
      "Sökes",
      "Tavlor",
      "UteÅterbrukat",
      "Vitvaror",
      "Återbygg",
    ],
    eng: [
      "kidsFurniture",
      "table",
      "other",
      "storageFurniture",
      "raiseAndLowerableDesk",
      "officeChair",
      "sparepart",
      "seatingFurniture",
      "desk",
      "sofaAndBench",
      "wanted",
      "painting",
      "outdoorItem",
      "appliances",
      "constructionMaterial",
    ],
  },
  {
    name: "description",
    fieldType: "textarea",
    disabled: false,
    title: "Beskrivning",
    placeholder: "Beskriv grejen...",
  },
  {
    name: "quantity",
    dataType: "number",
    fieldType: "input",
    disabled: false,
    title: "Antal",
    placeholder: "Hur många?",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "height",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Höjd",
    placeholder: "34 cm",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "width",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Bredd",
    placeholder: "34 cm",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "length",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Djup",
    placeholder: "34 cm",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "color",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Färg",
    placeholder: "Färg",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "material",
    dataType: "checkbox",
    fieldType: "input",
    disabled: false,
    title: "Material",
    option: [
      {
        name: "wood",
        swe: ["Trä"],
        eng: ["wood"],
      },
      {
        name: "plastic",
        swe: ["Plast"],
        eng: ["plastic"],
      },
      {
        name: "metal",
        swe: ["Metall"],
        eng: ["metal"],
      },
      {
        name: "other",
        swe: ["Annat"],
        eng: ["other"],
      },
    ],
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "condition",
    fieldType: "select",
    disabled: false,
    required: true,
    title: "Skick",
    swe: ["Nyskick", "Bra", "Sliten"],
    eng: ["Anew", "Bgood", "Cworn"],
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "areaOfUse",
    dataType: "checkbox",
    title: "Användningsområde",
    fieldType: "input",
    disabled: false,
    required: true,
    option: [
      {
        name: "indoors",
        swe: ["Inne"],
        eng: ["indoors"],
      },
      {
        name: "outside",
        swe: ["Ute"],
        eng: ["outside"],
      },
    ],
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "purchasePrice",
    dataType: "number",
    fieldType: "input",
    disabled: false,
    required: false,
    title: "Inköpspris",
    placeholder: "Inköpspris",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "missingItemsInformation",
    fieldType: "textarea",
    disabled: false,
    title: "Om det saknas något vid återlämning, gör så här",
    placeholder: "",
    condition: {
      field: "advertType",
      value: "borrow",
      operator: "==",
    },
  },
  {
    name: "pickUpInformation",
    fieldType: "textarea",
    disabled: false,
    title: "Bra att veta inför uthämtning",
    placeholder: "",
    condition: {
      field: "advertType",
      value: "borrow",
      operator: "==",
    },
  },
  {
    name: "returnInformation",
    fieldType: "textarea",
    disabled: false,
    title: "Hur du gör när du lämnar tillbaka prylen",
    placeholder: "",
    condition: {
      field: "advertType",
      value: "borrow",
      operator: "==",
    },
  },
  {
    name: "company",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Förvaltning",
    placeholder: "ex. Stadsledningsförvaltningen",
  },
  {
    name: "department",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Avdelning",
    placeholder: "ex. Digitaliseringsavdelningen",
  },
  {
    name: "location",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Adress",
    placeholder: "ex. Larmvägen 33 254 56 Helsingborg",
  },

  {
    name: "contactPerson",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Kontaktperson",
    placeholder: "Kontaktperson",
  },
  {
    name: "phoneNumber",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Telefon",
    placeholder: "ex. 0701234567",
  },
  {
    name: "email",
    dataType: "email",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Epost",
    placeholder: "namn.efternamn@helsingborg.se",
  },
];
