import { getCategoriesByParent, getCategoriesExceptByParent } from "../utils/handleCategories";
import { conditions, areaOfUse, materials } from "./advertMeta";

const recycleCategories = getCategoriesByParent([1]);
const borrowCategories = getCategoriesExceptByParent([1]);

export default [
  {
    name: "advertType",
    dataType: "text",
    fieldType: "radio",
    disabled: false,
    title: "Den är till för",
    required: true,
    options: [
      {
        id: 1,
        key: "recycle",
        title: "Återbruk",
      },
      {
        id: 2,
        key: "borrow",
        title: "Utlåning",
      },
    ],
  },
  {
    name: "images",
    dataType: "file",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Lägg till en bild",
  },
  {
    name: "title",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Rubrik",
    placeholder: "Döp annonsen...",
  },
  {
    name: "aterbruketId",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Återbruket ID",
    placeholder: "ex. 4435A",
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "category",
    fieldType: "select",
    disabled: false,
    required: true,
    title: "Kategori / Typ av möbel",
    options: recycleCategories,
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "category",
    fieldType: "select",
    disabled: false,
    required: true,
    title: "Kategori / Typ av sak",
    options: borrowCategories,
    condition: {
      field: "advertType",
      operator: "==",
      value: "borrow",
    },
  },
  {
    name: "description",
    fieldType: "textarea",
    disabled: false,
    title: "Beskrivning",
    placeholder: "Beskriv grejen...",
  },
  {
    name: "quantity",
    dataType: "number",
    fieldType: "input",
    disabled: false,
    title: "Antal",
    placeholder: "Hur många?",
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "height",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Höjd",
    placeholder: "34 cm",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "width",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Bredd",
    placeholder: "34 cm",
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "length",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Djup",
    placeholder: "34 cm",
    condition: {
      field: "advertType",
      value: "recycle",
      operator: "==",
    },
  },
  {
    name: "color",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Färg",
    placeholder: "Färg",
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "material",
    dataType: "checkbox",
    fieldType: "input",
    disabled: false,
    title: "Material",
    options: materials,
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "condition",
    fieldType: "select",
    disabled: false,
    required: true,
    title: "Skick",
    options: conditions,
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "areaOfUse",
    dataType: "checkbox",
    title: "Användningsområde",
    fieldType: "input",
    disabled: false,
    required: true,
    options: areaOfUse,
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "purchasePrice",
    dataType: "number",
    fieldType: "input",
    disabled: false,
    required: false,
    title: "Inköpspris",
    placeholder: "Inköpspris",
    condition: {
      field: "advertType",
      operator: "==",
      value: "recycle",
    },
  },
  {
    name: "missingItemsInformation",
    fieldType: "textarea",
    disabled: false,
    title: "Om det saknas något vid återlämning, gör så här",
    placeholder: "",
    condition: {
      field: "advertType",
      operator: "==",
      value: "borrow",
    },
  },
  {
    name: "pickUpInformation",
    fieldType: "textarea",
    disabled: false,
    title: "Bra att veta inför uthämtning",
    placeholder: "",
    condition: {
      field: "advertType",
      operator: "==",
      value: "borrow",
    },
  },
  {
    name: "returnInformation",
    fieldType: "textarea",
    disabled: false,
    title: "Hur du gör när du lämnar tillbaka prylen",
    placeholder: "",
    condition: {
      field: "advertType",
      operator: "==",
      value: "borrow",
    },
  },
  {
    name: "company",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Förvaltning",
    placeholder: "ex. Stadsledningsförvaltningen",
  },
  {
    name: "department",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Avdelning",
    placeholder: "ex. Digitaliseringsavdelningen",
  },
  {
    name: "location",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Adress",
    placeholder: "ex. Larmvägen 33 254 56 Helsingborg",
  },
  {
    name: "contactPerson",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Kontaktperson",
    placeholder: "Kontaktperson",
  },
  {
    name: "phoneNumber",
    dataType: "text",
    fieldType: "input",
    disabled: false,
    title: "Telefon",
    placeholder: "ex. 0701234567",
  },
  {
    name: "email",
    dataType: "email",
    fieldType: "input",
    disabled: false,
    required: true,
    title: "Epost",
    placeholder: "namn.efternamn@helsingborg.se",
  },
];
